name: Demo manual

on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: "Introduce mensaje de texto"
        required: true
        type: string

jobs:
  imprime-mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensaje
        run: echo "${{ github.event.inputs.mensaje }}"
